# Collecting Province-Level OCDS Data
Notebook ini mengambil katalog LPSE langsung dari API master OpenTender, memfilter LPSE level provinsi, lalu mengunduh batch OCDS untuk semua provinsi yang tersedia.

## 0. Imports and Global Configuration

In [2]:
import csv
import json
import re
import time
import zipfile
from pathlib import Path

import pandas as pd
import requests
from IPython.display import display

In [3]:
base_location_url = 'https://pro.opentender.net/api/master/lpse/'
base_export_url = 'https://opentender.net/api/tender/export-ocds-batch/'
years = list(range(2015, 2025))
request_timeout = 120
sleep_seconds = 1

json_root = Path('../data/json')
csv_root = Path('../data/csv')
master_csv_path = csv_root / 'master_data_ocds.csv'
summary_csv_path = csv_root / 'raw_data_summary_by_daerah.csv'
all_lspe_catalog_path = csv_root / 'lpse_catalog_all.csv'
province_catalog_path = csv_root / 'lpse_province_catalog.csv'

fieldnames = [
    'lspe_id', 'nama_daerah', 'source_year', 'source_file', 'ocid', 'release_id', 'date',
    'buyer_name', 'buyer_id', 'tender_id', 'tender_title', 'mainProcurementCategory',
    'tender_minValue', 'tender_datePublished', 'tender_status', 'award_id', 'award_title',
    'award_date', 'award_value', 'award_supplier'
]

PROVINCE_NAME_OVERRIDES = {
    'Dki Jakarta': 'DKI Jakarta',
    'Daerah Istimewa Yogyakarta': 'Daerah Istimewa Yogyakarta',
}

json_root.mkdir(parents=True, exist_ok=True)
csv_root.mkdir(parents=True, exist_ok=True)

## 1. Fetch LPSE Catalog and Build Province Targets

In [ ]:
import re
import time

import pandas as pd
import requests

def normalize_whitespace(text: str) -> str:
    return re.sub(r'\s+', ' ', str(text or '')).strip()

# reformatting region so normalized name can be used for grouping and matching with other datasets
def format_region_name(name: str) -> str:
    title_name = normalize_whitespace(name).title()
    return PROVINCE_NAME_OVERRIDES.get(title_name, title_name)

# extract nama provinsi & exceptional handling kalsel
def extract_province_name(lpse_name: str):
    cleaned = normalize_whitespace(lpse_name)
    match = re.match(r'(?i)^lpse\s+provinsi\s+(.+)$', cleaned)
    if match:
        return format_region_name(match.group(1))

    if cleaned.casefold() == 'lpse kalimantan selatan':
        return 'Kalimantan Selatan'

    return None

# fetch LPSE
def fetch_lpse_catalog(api_url: str) -> pd.DataFrame:
    next_url = f'{api_url}?page_size=1000'
    rows = []

    while next_url:
        response = requests.get(next_url, timeout=request_timeout)
        response.raise_for_status()
        payload = response.json()

        page_rows = payload.get('results', []) or []
        rows.extend(page_rows)
        total_count = payload.get('count', len(rows))
        print(f'[catalog] fetched {len(rows):,} / {total_count:,} LPSE rows')

        next_url = (payload.get('links') or {}).get('next')
        time.sleep(0.2)

    catalog = pd.DataFrame(rows)
    if catalog.empty:
        raise RuntimeError('LPSE catalog API returned no rows.')

    catalog = catalog.rename(columns={'code': 'lspe_id', 'name': 'lpse_name_raw'})
    catalog['lspe_id'] = catalog['lspe_id'].astype(str).str.strip()
    catalog['lpse_name_raw'] = catalog['lpse_name_raw'].astype(str).map(normalize_whitespace)
    catalog = catalog.drop_duplicates(subset=['lspe_id']).sort_values(['lpse_name_raw', 'lspe_id']).reset_index(drop=True)
    return catalog

In [ ]:
# call fetch lpse function 
lpse_catalog_all = fetch_lpse_catalog(base_location_url)
lpse_catalog_all.to_csv(all_lspe_catalog_path, index=False)

# take only provinsi level LPSE and extract province name
province_catalog = lpse_catalog_all.copy()
province_catalog['nama_daerah'] = province_catalog['lpse_name_raw'].apply(extract_province_name)
province_catalog = (
    province_catalog.dropna(subset=['nama_daerah'])
    [['lspe_id', 'nama_daerah', 'lpse_name_raw']]
    .sort_values(['nama_daerah', 'lspe_id'])
    .reset_index(drop=True)
)
province_catalog.to_csv(province_catalog_path, index=False)

# error handling not found or else
target_lspe_df = province_catalog[['lspe_id', 'nama_daerah']].copy()

if target_lspe_df.empty:
    raise RuntimeError('Tidak ada LPSE level provinsi yang berhasil dipetakan dari catalog API.')

# result of lpse
print('Target LPSE provinsi:')
display(target_lspe_df)
print(f'Total province LPSE found: {len(target_lspe_df):,}')
print(f'Years covered: {years[0]} - {years[-1]}')
print('Notebook mode: always redownload and rewrite raw master CSV')
print(f'Saved full catalog     : {all_lspe_catalog_path.resolve()}')
print(f'Saved province catalog : {province_catalog_path.resolve()}')

[catalog] fetched 616 / 616 LPSE rows
Target LPSE provinsi:

   lspe_id                 nama_daerah
0      106                        Aceh
1       33                        Bali
2       99                      Banten
3      267                    Bengkulu
4      127                 DKI Jakarta
5       13  Daerah Istimewa Yogyakarta
6       18                   Gorontalo
7       70                       Jambi
8       14                  Jawa Barat
9       42                 Jawa Tengah
10      15                  Jawa Timur
11      97            Kalimantan Barat
12     181          Kalimantan Selatan
13      12           Kalimantan Tengah
14      35            Kalimantan Timur
15     716            Kalimantan Utara
16      86   Kepulauan Bangka Belitung
17      22              Kepulauan Riau
18     121                     Lampung
19     288                      Maluku
20     361                Maluku Utara
21      37         Nusa Tenggara Barat
22     131         Nusa Tenggara Timur
23      41                       Papua
24     641                 Papua Barat
25      39                        Riau
26     263              Sulawesi Barat
27      36            Sulawesi Selatan
28     154             Sulawesi Tengah
29      81           Sulawesi Tenggara
30     173              Sulawesi Utara
31      16              Sumatera Barat
32     103            Sumatera Selatan
33      27              Sumatera Utara

Total province LPSE found: 34
Years covered: 2015 - 2024
Notebook mode: always redownload and rewrite raw master CSV
Saved full catalog     : C:\Users\VICTUS\coding\collab\3\data\csv\lpse_catalog_all.csv
Saved province catalog : C:\Users\VICTUS\coding\collab\3\data\csv\lpse_province_catalog.csv

## 2. Download Helper

In [ ]:
# formatting name for ocds data
def expected_json_path(lspe_id, year):
    return json_root / lspe_id / f'ocds-data-tender-{year}-{lspe_id}.json'

# download, extract, and save JSON batch with error handling and delay
def download_json_batch(lspe_id, nama_daerah, year):
    # target dir
    target_path = expected_json_path(lspe_id, year)
    target_path.parent.mkdir(parents=True, exist_ok=True)

    # downlaod zip, extract json, save, and cleanup
    zip_path = Path(f'ocds_{lspe_id}_{year}.zip')
    target_url = f'{base_export_url}?year={year}&lpse={lspe_id}'
    print(f'[download] {nama_daerah} ({lspe_id}) {year}')

    response = requests.get(target_url, stream=True, timeout=request_timeout)
    response.raise_for_status()

    with open(zip_path, 'wb') as file_handle:
        for chunk in response.iter_content(chunk_size=8192):
            # write data to file
            if chunk:
                file_handle.write(chunk)

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        json_members = [member for member in zip_ref.namelist() if member.endswith('.json')]
        if not json_members:
            raise ValueError(f'No JSON file found inside {zip_path.name}')

        member = json_members[0]
        zip_ref.extract(member, target_path.parent)
        extracted_path = target_path.parent / Path(member).name

        if target_path.exists():
            target_path.unlink()

        extracted_path.rename(target_path)

    zip_path.unlink(missing_ok=True)
    time.sleep(sleep_seconds)
    return target_path

## 3. Download All Province Files

In [7]:
for row in target_lspe_df.itertuples(index=False):
    lspe_id = str(row.lspe_id)
    nama_daerah = row.nama_daerah

    print('=' * 70)
    print(f'DOWNLOADING {nama_daerah} ({lspe_id})')
    print('=' * 70)

    for year in years:
        try:
            download_json_batch(lspe_id, nama_daerah, year)
        except Exception as exc:
            print(f'[error] {nama_daerah} ({lspe_id}) {year}: {exc}')

======================================================================
DOWNLOADING Aceh (106)
======================================================================
[download] Aceh (106) 2015
[download] Aceh (106) 2016
[download] Aceh (106) 2017
[download] Aceh (106) 2018
[download] Aceh (106) 2019
[download] Aceh (106) 2020
[download] Aceh (106) 2021
[download] Aceh (106) 2022
[download] Aceh (106) 2023
[download] Aceh (106) 2024
[error] Aceh (106) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=106
======================================================================
DOWNLOADING Bali (33)
======================================================================
[download] Bali (33) 2015
[download] Bali (33) 2016
[download] Bali (33) 2017
[download] Bali (33) 2018
[download] Bali (33) 2019
[download] Bali (33) 2020
[download] Bali (33) 2021
[download] Bali (33) 2022
[download] Bali (33) 2023
[download] Bali (33) 2024
[error] Bali (33) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=33
======================================================================
DOWNLOADING Banten (99)
======================================================================
[download] Banten (99) 2015
[download] Banten (99) 2016
[download] Banten (99) 2017
[download] Banten (99) 2018
[download] Banten (99) 2019
[download] Banten (99) 2020
[download] Banten (99) 2021
[download] Banten (99) 2022
[download] Banten (99) 2023
[download] Banten (99) 2024
[error] Banten (99) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=99
======================================================================
DOWNLOADING Bengkulu (267)
======================================================================
[download] Bengkulu (267) 2015
[download] Bengkulu (267) 2016
[download] Bengkulu (267) 2017
[download] Bengkulu (267) 2018
[download] Bengkulu (267) 2019
[download] Bengkulu (267) 2020
[download] Bengkulu (267) 2021
[download] Bengkulu (267) 2022
[download] Bengkulu (267) 2023
[download] Bengkulu (267) 2024
[error] Bengkulu (267) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=267
======================================================================
DOWNLOADING DKI Jakarta (127)
======================================================================
[download] DKI Jakarta (127) 2015
[download] DKI Jakarta (127) 2016
[download] DKI Jakarta (127) 2017
[download] DKI Jakarta (127) 2018
[download] DKI Jakarta (127) 2019
[download] DKI Jakarta (127) 2020
[download] DKI Jakarta (127) 2021
[download] DKI Jakarta (127) 2022
[download] DKI Jakarta (127) 2023
[download] DKI Jakarta (127) 2024
[error] DKI Jakarta (127) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=127
======================================================================
DOWNLOADING Daerah Istimewa Yogyakarta (13)
======================================================================
[download] Daerah Istimewa Yogyakarta (13) 2015
[download] Daerah Istimewa Yogyakarta (13) 2016
[download] Daerah Istimewa Yogyakarta (13) 2017
[download] Daerah Istimewa Yogyakarta (13) 2018
[download] Daerah Istimewa Yogyakarta (13) 2019
[download] Daerah Istimewa Yogyakarta (13) 2020
[download] Daerah Istimewa Yogyakarta (13) 2021
[download] Daerah Istimewa Yogyakarta (13) 2022
[download] Daerah Istimewa Yogyakarta (13) 2023
[download] Daerah Istimewa Yogyakarta (13) 2024
======================================================================
DOWNLOADING Gorontalo (18)
======================================================================
[download] Gorontalo (18) 2015
[download] Gorontalo (18) 2016
[download] Gorontalo (18) 2017
[download] Gorontalo (18) 2018
[download] Gorontalo (18) 2019
[download] Gorontalo (18) 2020
[download] Gorontalo (18) 2021
[download] Gorontalo (18) 2022
[download] Gorontalo (18) 2023
[download] Gorontalo (18) 2024
======================================================================
DOWNLOADING Jambi (70)
======================================================================
[download] Jambi (70) 2015
[download] Jambi (70) 2016
[download] Jambi (70) 2017
[download] Jambi (70) 2018
[download] Jambi (70) 2019
[download] Jambi (70) 2020
[download] Jambi (70) 2021
[download] Jambi (70) 2022
[download] Jambi (70) 2023
[download] Jambi (70) 2024
[error] Jambi (70) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=70
======================================================================
DOWNLOADING Jawa Barat (14)
======================================================================
[download] Jawa Barat (14) 2015
[download] Jawa Barat (14) 2016
[download] Jawa Barat (14) 2017
[download] Jawa Barat (14) 2018
[download] Jawa Barat (14) 2019
[download] Jawa Barat (14) 2020
[download] Jawa Barat (14) 2021
[download] Jawa Barat (14) 2022
[download] Jawa Barat (14) 2023
[download] Jawa Barat (14) 2024
======================================================================
DOWNLOADING Jawa Tengah (42)
======================================================================
[download] Jawa Tengah (42) 2015
[download] Jawa Tengah (42) 2016
[download] Jawa Tengah (42) 2017
[download] Jawa Tengah (42) 2018
[download] Jawa Tengah (42) 2019
[download] Jawa Tengah (42) 2020
[download] Jawa Tengah (42) 2021
[download] Jawa Tengah (42) 2022
[download] Jawa Tengah (42) 2023
[download] Jawa Tengah (42) 2024
[error] Jawa Tengah (42) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=42
======================================================================
DOWNLOADING Jawa Timur (15)
======================================================================
[download] Jawa Timur (15) 2015
[download] Jawa Timur (15) 2016
[download] Jawa Timur (15) 2017
[download] Jawa Timur (15) 2018
[download] Jawa Timur (15) 2019
[download] Jawa Timur (15) 2020
[download] Jawa Timur (15) 2021
[download] Jawa Timur (15) 2022
[download] Jawa Timur (15) 2023
[download] Jawa Timur (15) 2024
======================================================================
DOWNLOADING Kalimantan Barat (97)
======================================================================
[download] Kalimantan Barat (97) 2015
[download] Kalimantan Barat (97) 2016
[download] Kalimantan Barat (97) 2017
[download] Kalimantan Barat (97) 2018
[download] Kalimantan Barat (97) 2019
[download] Kalimantan Barat (97) 2020
[download] Kalimantan Barat (97) 2021
[download] Kalimantan Barat (97) 2022
[download] Kalimantan Barat (97) 2023
[download] Kalimantan Barat (97) 2024
[error] Kalimantan Barat (97) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=97
======================================================================
DOWNLOADING Kalimantan Selatan (181)
======================================================================
[download] Kalimantan Selatan (181) 2015
[download] Kalimantan Selatan (181) 2016
[download] Kalimantan Selatan (181) 2017
[download] Kalimantan Selatan (181) 2018
[download] Kalimantan Selatan (181) 2019
[download] Kalimantan Selatan (181) 2020
[download] Kalimantan Selatan (181) 2021
[download] Kalimantan Selatan (181) 2022
[download] Kalimantan Selatan (181) 2023
[download] Kalimantan Selatan (181) 2024
[error] Kalimantan Selatan (181) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=181
======================================================================
DOWNLOADING Kalimantan Tengah (12)
======================================================================
[download] Kalimantan Tengah (12) 2015
[download] Kalimantan Tengah (12) 2016
[download] Kalimantan Tengah (12) 2017
[download] Kalimantan Tengah (12) 2018
[download] Kalimantan Tengah (12) 2019
[download] Kalimantan Tengah (12) 2020
[download] Kalimantan Tengah (12) 2021
[download] Kalimantan Tengah (12) 2022
[download] Kalimantan Tengah (12) 2023
[download] Kalimantan Tengah (12) 2024
======================================================================
DOWNLOADING Kalimantan Timur (35)
======================================================================
[download] Kalimantan Timur (35) 2015
[download] Kalimantan Timur (35) 2016
[download] Kalimantan Timur (35) 2017
[download] Kalimantan Timur (35) 2018
[download] Kalimantan Timur (35) 2019
[download] Kalimantan Timur (35) 2020
[download] Kalimantan Timur (35) 2021
[download] Kalimantan Timur (35) 2022
[download] Kalimantan Timur (35) 2023
[download] Kalimantan Timur (35) 2024
[error] Kalimantan Timur (35) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=35
======================================================================
DOWNLOADING Kalimantan Utara (716)
======================================================================
[download] Kalimantan Utara (716) 2015
[download] Kalimantan Utara (716) 2016
[download] Kalimantan Utara (716) 2017
[download] Kalimantan Utara (716) 2018
[download] Kalimantan Utara (716) 2019
[download] Kalimantan Utara (716) 2020
[download] Kalimantan Utara (716) 2021
[download] Kalimantan Utara (716) 2022
[download] Kalimantan Utara (716) 2023
[download] Kalimantan Utara (716) 2024
[error] Kalimantan Utara (716) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=716
======================================================================
DOWNLOADING Kepulauan Bangka Belitung (86)
======================================================================
[download] Kepulauan Bangka Belitung (86) 2015
[download] Kepulauan Bangka Belitung (86) 2016
[download] Kepulauan Bangka Belitung (86) 2017
[download] Kepulauan Bangka Belitung (86) 2018
[download] Kepulauan Bangka Belitung (86) 2019
[download] Kepulauan Bangka Belitung (86) 2020
[download] Kepulauan Bangka Belitung (86) 2021
[download] Kepulauan Bangka Belitung (86) 2022
[download] Kepulauan Bangka Belitung (86) 2023
[download] Kepulauan Bangka Belitung (86) 2024
[error] Kepulauan Bangka Belitung (86) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=86
======================================================================
DOWNLOADING Kepulauan Riau (22)
======================================================================
[download] Kepulauan Riau (22) 2015
[download] Kepulauan Riau (22) 2016
[download] Kepulauan Riau (22) 2017
[download] Kepulauan Riau (22) 2018
[download] Kepulauan Riau (22) 2019
[download] Kepulauan Riau (22) 2020
[download] Kepulauan Riau (22) 2021
[download] Kepulauan Riau (22) 2022
[download] Kepulauan Riau (22) 2023
[download] Kepulauan Riau (22) 2024
======================================================================
DOWNLOADING Lampung (121)
======================================================================
[download] Lampung (121) 2015
[download] Lampung (121) 2016
[download] Lampung (121) 2017
[download] Lampung (121) 2018
[download] Lampung (121) 2019
[download] Lampung (121) 2020
[download] Lampung (121) 2021
[download] Lampung (121) 2022
[download] Lampung (121) 2023
[download] Lampung (121) 2024
[error] Lampung (121) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=121
======================================================================
DOWNLOADING Maluku (288)
======================================================================
[download] Maluku (288) 2015
[download] Maluku (288) 2016
[download] Maluku (288) 2017
[download] Maluku (288) 2018
[download] Maluku (288) 2019
[download] Maluku (288) 2020
[download] Maluku (288) 2021
[download] Maluku (288) 2022
[download] Maluku (288) 2023
[download] Maluku (288) 2024
[error] Maluku (288) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=288
======================================================================
DOWNLOADING Maluku Utara (361)
======================================================================
[download] Maluku Utara (361) 2015
[download] Maluku Utara (361) 2016
[download] Maluku Utara (361) 2017
[download] Maluku Utara (361) 2018
[download] Maluku Utara (361) 2019
[download] Maluku Utara (361) 2020
[download] Maluku Utara (361) 2021
[download] Maluku Utara (361) 2022
[download] Maluku Utara (361) 2023
[download] Maluku Utara (361) 2024
[error] Maluku Utara (361) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=361
======================================================================
DOWNLOADING Nusa Tenggara Barat (37)
======================================================================
[download] Nusa Tenggara Barat (37) 2015
[download] Nusa Tenggara Barat (37) 2016
[download] Nusa Tenggara Barat (37) 2017
[download] Nusa Tenggara Barat (37) 2018
[download] Nusa Tenggara Barat (37) 2019
[download] Nusa Tenggara Barat (37) 2020
[download] Nusa Tenggara Barat (37) 2021
[download] Nusa Tenggara Barat (37) 2022
[download] Nusa Tenggara Barat (37) 2023
[download] Nusa Tenggara Barat (37) 2024
[error] Nusa Tenggara Barat (37) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=37
======================================================================
DOWNLOADING Nusa Tenggara Timur (131)
======================================================================
[download] Nusa Tenggara Timur (131) 2015
[download] Nusa Tenggara Timur (131) 2016
[download] Nusa Tenggara Timur (131) 2017
[download] Nusa Tenggara Timur (131) 2018
[download] Nusa Tenggara Timur (131) 2019
[download] Nusa Tenggara Timur (131) 2020
[download] Nusa Tenggara Timur (131) 2021
[download] Nusa Tenggara Timur (131) 2022
[download] Nusa Tenggara Timur (131) 2023
[download] Nusa Tenggara Timur (131) 2024
[error] Nusa Tenggara Timur (131) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=131
======================================================================
DOWNLOADING Papua (41)
======================================================================
[download] Papua (41) 2015
[download] Papua (41) 2016
[download] Papua (41) 2017
[download] Papua (41) 2018
[download] Papua (41) 2019
[download] Papua (41) 2020
[download] Papua (41) 2021
[download] Papua (41) 2022
[download] Papua (41) 2023
[download] Papua (41) 2024
[error] Papua (41) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=41
======================================================================
DOWNLOADING Papua Barat (641)
======================================================================
[download] Papua Barat (641) 2015
[download] Papua Barat (641) 2016
[download] Papua Barat (641) 2017
[download] Papua Barat (641) 2018
[download] Papua Barat (641) 2019
[download] Papua Barat (641) 2020
[download] Papua Barat (641) 2021
[download] Papua Barat (641) 2022
[download] Papua Barat (641) 2023
[download] Papua Barat (641) 2024
[error] Papua Barat (641) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=641
======================================================================
DOWNLOADING Riau (39)
======================================================================
[download] Riau (39) 2015
[download] Riau (39) 2016
[download] Riau (39) 2017
[download] Riau (39) 2018
[download] Riau (39) 2019
[download] Riau (39) 2020
[download] Riau (39) 2021
[download] Riau (39) 2022
[download] Riau (39) 2023
[download] Riau (39) 2024
[error] Riau (39) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=39
======================================================================
DOWNLOADING Sulawesi Barat (263)
======================================================================
[download] Sulawesi Barat (263) 2015
[download] Sulawesi Barat (263) 2016
[download] Sulawesi Barat (263) 2017
[download] Sulawesi Barat (263) 2018
[download] Sulawesi Barat (263) 2019
[download] Sulawesi Barat (263) 2020
[download] Sulawesi Barat (263) 2021
[download] Sulawesi Barat (263) 2022
[download] Sulawesi Barat (263) 2023
[download] Sulawesi Barat (263) 2024
[error] Sulawesi Barat (263) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=263
======================================================================
DOWNLOADING Sulawesi Selatan (36)
======================================================================
[download] Sulawesi Selatan (36) 2015
[download] Sulawesi Selatan (36) 2016
[download] Sulawesi Selatan (36) 2017
[download] Sulawesi Selatan (36) 2018
[download] Sulawesi Selatan (36) 2019
[download] Sulawesi Selatan (36) 2020
[download] Sulawesi Selatan (36) 2021
[download] Sulawesi Selatan (36) 2022
[download] Sulawesi Selatan (36) 2023
[download] Sulawesi Selatan (36) 2024
[error] Sulawesi Selatan (36) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=36
======================================================================
DOWNLOADING Sulawesi Tengah (154)
======================================================================
[download] Sulawesi Tengah (154) 2015
[download] Sulawesi Tengah (154) 2016
[download] Sulawesi Tengah (154) 2017
[download] Sulawesi Tengah (154) 2018
[download] Sulawesi Tengah (154) 2019
[download] Sulawesi Tengah (154) 2020
[download] Sulawesi Tengah (154) 2021
[download] Sulawesi Tengah (154) 2022
[download] Sulawesi Tengah (154) 2023
[download] Sulawesi Tengah (154) 2024
[error] Sulawesi Tengah (154) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=154
======================================================================
DOWNLOADING Sulawesi Tenggara (81)
======================================================================
[download] Sulawesi Tenggara (81) 2015
[download] Sulawesi Tenggara (81) 2016
[download] Sulawesi Tenggara (81) 2017
[download] Sulawesi Tenggara (81) 2018
[download] Sulawesi Tenggara (81) 2019
[download] Sulawesi Tenggara (81) 2020
[download] Sulawesi Tenggara (81) 2021
[download] Sulawesi Tenggara (81) 2022
[download] Sulawesi Tenggara (81) 2023
[download] Sulawesi Tenggara (81) 2024
[error] Sulawesi Tenggara (81) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=81
======================================================================
DOWNLOADING Sulawesi Utara (173)
======================================================================
[download] Sulawesi Utara (173) 2015
[download] Sulawesi Utara (173) 2016
[download] Sulawesi Utara (173) 2017
[download] Sulawesi Utara (173) 2018
[download] Sulawesi Utara (173) 2019
[download] Sulawesi Utara (173) 2020
[download] Sulawesi Utara (173) 2021
[download] Sulawesi Utara (173) 2022
[download] Sulawesi Utara (173) 2023
[download] Sulawesi Utara (173) 2024
[error] Sulawesi Utara (173) 2024: 404 Client Error: Not Found for url: https://opentender.net/api/tender/export-ocds-batch/?year=2024&lpse=173
======================================================================
DOWNLOADING Sumatera Barat (16)
======================================================================
[download] Sumatera Barat (16) 2015
[download] Sumatera Barat (16) 2016
[download] Sumatera Barat (16) 2017

## 4. Convert JSON into One Raw Master CSV

In [ ]:
total_rows_global = 0
summary_rows = []

with open(master_csv_path, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()

    # implement everything so far
    for row in target_lspe_df.itertuples(index=False):
        # find everything json to extract
        lspe_id = str(row.lspe_id)
        nama_daerah = row.nama_daerah
        region_dir = json_root / lspe_id
        files = sorted(region_dir.glob(f'ocds-data-tender-*-{lspe_id}.json'))

        if not files:
            print(f'[warning] no files found for {nama_daerah} ({lspe_id})')
            summary_rows.append({
                'lspe_id': lspe_id,
                'nama_daerah': nama_daerah,
                'json_files': 0,
                'rows': 0,
                'min_award_date': None,
                'max_award_date': None,
            })
            continue

        print('=' * 70)
        print(f'PROCESSING {nama_daerah} ({lspe_id})')
        print('=' * 70)

        rows_per_region = 0
        award_dates = []

        # loop through files and extract data
        for file_path in files:
            try:
                payload = json.loads(file_path.read_text(encoding='utf-8'))
            except Exception as exc:
                print(f'[warning] failed reading {file_path.name}: {exc}')
                continue

            source_year = file_path.stem.split('-')[-2]
            for release in payload.get('releases', []):
                tender = release.get('tender', {}) or {}
                buyer = release.get('buyer', {}) or {}
                awards = release.get('awards', []) or []

                for award in awards:
                    suppliers = award.get('suppliers', []) or []
                    supplier_names = ', '.join([supplier.get('name', '') for supplier in suppliers if supplier.get('name')]) or None

                    writer.writerow({
                        'lspe_id': lspe_id,
                        'nama_daerah': nama_daerah,
                        'source_year': source_year,
                        'source_file': file_path.name,
                        'ocid': release.get('ocid'),
                        'release_id': release.get('id'),
                        'date': release.get('date'),
                        'buyer_name': buyer.get('name'),
                        'buyer_id': buyer.get('id'),
                        'tender_id': tender.get('id'),
                        'tender_title': tender.get('title'),
                        'mainProcurementCategory': tender.get('mainProcurementCategory'),
                        'tender_minValue': (tender.get('minValue') or {}).get('amount'),
                        'tender_datePublished': tender.get('datePublished'),
                        'tender_status': tender.get('status'),
                        'award_id': award.get('id'),
                        'award_title': award.get('title'),
                        'award_date': award.get('date'),
                        'award_value': (award.get('value') or {}).get('amount'),
                        'award_supplier': supplier_names,
                    })

                    if award.get('date'):
                        award_dates.append(award.get('date'))

                    rows_per_region += 1
                    total_rows_global += 1

        print(f'Rows written: {rows_per_region:,}')
        print(f'Files found : {len(files)}')

        summary_rows.append({
            'lspe_id': lspe_id,
            'nama_daerah': nama_daerah,
            'json_files': len(files),
            'rows': rows_per_region,
            'min_award_date': min(award_dates) if award_dates else None,
            'max_award_date': max(award_dates) if award_dates else None,
        })

======================================================================
PROCESSING Aceh (106)
======================================================================
Rows written: 12,475
Files found : 9
======================================================================
PROCESSING Bali (33)
======================================================================
Rows written: 1,934
Files found : 9
======================================================================
PROCESSING Banten (99)
======================================================================
Rows written: 3,452
Files found : 9
======================================================================
PROCESSING Bengkulu (267)
======================================================================
Rows written: 1,974
Files found : 9
======================================================================
PROCESSING DKI Jakarta (127)
======================================================================
Rows written: 8,678
Files found : 9
======================================================================
PROCESSING Daerah Istimewa Yogyakarta (13)
======================================================================
Rows written: 4,537
Files found : 10
======================================================================
PROCESSING Gorontalo (18)
======================================================================
Rows written: 1,629
Files found : 10
======================================================================
PROCESSING Jambi (70)
======================================================================
Rows written: 3,001
Files found : 9
======================================================================
PROCESSING Jawa Barat (14)
======================================================================
Rows written: 10,629
Files found : 10
======================================================================
PROCESSING Jawa Tengah (42)
======================================================================
Rows written: 6,038
Files found : 9
======================================================================
PROCESSING Jawa Timur (15)
======================================================================
Rows written: 6,440
Files found : 10
======================================================================
PROCESSING Kalimantan Barat (97)
======================================================================
Rows written: 3,015
Files found : 9
======================================================================
PROCESSING Kalimantan Selatan (181)
======================================================================
Rows written: 2,460
Files found : 9
======================================================================
PROCESSING Kalimantan Tengah (12)
======================================================================
Rows written: 4,120
Files found : 10
======================================================================
PROCESSING Kalimantan Timur (35)
======================================================================
Rows written: 4,053
Files found : 9
======================================================================
PROCESSING Kalimantan Utara (716)
======================================================================
Rows written: 1,897
Files found : 9
======================================================================
PROCESSING Kepulauan Bangka Belitung (86)
======================================================================
Rows written: 1,342
Files found : 9
======================================================================
PROCESSING Kepulauan Riau (22)
======================================================================
Rows written: 2,777
Files found : 10
======================================================================
PROCESSING Lampung (121)
======================================================================
Rows written: 7,083
Files found : 9
======================================================================
PROCESSING Maluku (288)
======================================================================
Rows written: 5,937
Files found : 9
======================================================================
PROCESSING Maluku Utara (361)
======================================================================
Rows written: 4,572
Files found : 9
======================================================================
PROCESSING Nusa Tenggara Barat (37)
======================================================================
Rows written: 1,818
Files found : 9
======================================================================
PROCESSING Nusa Tenggara Timur (131)
======================================================================
Rows written: 3,368
Files found : 9
======================================================================
PROCESSING Papua (41)
======================================================================
Rows written: 3,560
Files found : 9
======================================================================
PROCESSING Papua Barat (641)
======================================================================
Rows written: 2,711
Files found : 9
======================================================================
PROCESSING Riau (39)
======================================================================
Rows written: 4,666
Files found : 9
======================================================================
PROCESSING Sulawesi Barat (263)
======================================================================
Rows written: 1,465
Files found : 9
======================================================================
PROCESSING Sulawesi Selatan (36)
======================================================================
Rows written: 3,556
Files found : 9
======================================================================
PROCESSING Sulawesi Tengah (154)
======================================================================
Rows written: 2,182
Files found : 9
======================================================================
PROCESSING Sulawesi Tenggara (81)
======================================================================
Rows written: 5,292
Files found : 9
======================================================================
PROCESSING Sulawesi Utara (173)
======================================================================
Rows written: 3,399
Files found : 9
======================================================================
PROCESSING Sumatera Barat (16)
======================================================================
Rows written: 4,150
Files found : 10
======================================================================
PROCESSING Sumatera Selatan (103)
======================================================================
Rows written: 5,930
Files found : 9
======================================================================
PROCESSING Sumatera Utara (27)
======================================================================
Rows written: 5,782
Files found : 10

## 5. Final Summary and Save Diagnostics

In [9]:
summary_df = pd.DataFrame(summary_rows).sort_values(['nama_daerah', 'lspe_id']).reset_index(drop=True)
summary_df.to_csv(summary_csv_path, index=False)

print('RAW COLLECTION SUMMARY')
print('=' * 70)
display(summary_df)

print('Saved files:')
print(f'- Master CSV         : {master_csv_path.resolve()}')
print(f'- Summary CSV        : {summary_csv_path.resolve()}')
print(f'- LPSE Catalog (all) : {all_lspe_catalog_path.resolve()}')
print(f'- LPSE Catalog prov  : {province_catalog_path.resolve()}')
print(f'- Total rows         : {total_rows_global:,}')

RAW COLLECTION SUMMARY
======================================================================

,lspe_id,nama_daerah,json_files,rows,min_award_date,max_award_date
0,106,Aceh,9,12475,2015-03-09T00:00:00.000000Z,2023-10-25T00:00:00.000000Z
1,33,Bali,9,1934,2014-12-10T00:00:00.000000Z,2023-10-10T00:00:00.000000Z
2,99,Banten,9,3452,2015-01-13T00:00:00.000000Z,2023-11-02T00:00:00.000000Z
3,267,Bengkulu,9,1974,2015-02-15T00:00:00.000000Z,2023-11-06T00:00:00.000000Z
4,127,DKI Jakarta,9,8678,2014-12-24T00:00:00.000000Z,2023-10-18T00:00:00.000000Z
5,13,Daerah Istimewa Yogyakarta,10,4537,2015-01-23T00:00:00.000000Z,2024-10-24T14:00:00.000000Z
6,18,Gorontalo,10,1629,2014-12-21T00:00:00.000000Z,2024-09-13T15:30:00.000000Z
7,70,Jambi,9,3001,1-01-01T00:00:00.000000Z,2023-09-30T00:00:00.000000Z
8,14,Jawa Barat,10,10629,2014-12-15T00:00:00.000000Z,2024-11-21T11:00:00.000000Z
9,42,Jawa Tengah,9,6038,2014-11-29T00:00:00.000000Z,2023-10-16T00:00:00.000000Z
10,15,Jawa Timur,10,6440,2014-12-19T00:00:00.000000Z,2024-10-02T15:00:00.000000Z
11,97,Kalimantan Barat,9,3015,2014-12-18T00:00:00.000000Z,2023-11-10T00:00:00.000000Z
12,181,Kalimantan Selatan,9,2460,2015-02-03T00:00:00.000000Z,2023-11-01T00:00:00.000000Z
13,12,Kalimantan Tengah,10,4120,2014-12-24T00:00:00.000000Z,2024-11-24T07:00:00.000000Z
14,35,Kalimantan Timur,9,4053,2014-12-22T00:00:00.000000Z,2023-11-15T00:00:00.000000Z
15,716,Kalimantan Utara,9,1897,2015-10-23T00:00:00.000000Z,2023-11-06T00:00:00.000000Z
16,86,Kepulauan Bangka Belitung,9,1342,2015-01-21T00:00:00.000000Z,2023-11-03T00:00:00.000000Z
17,22,Kepulauan Riau,10,2777,2015-01-24T00:00:00.000000Z,2024-10-25T16:00:00.000000Z
18,121,Lampung,9,7083,2015-02-18T00:00:00.000000Z,2024-03-04T00:00:00.000000Z
19,288,Maluku,9,5937,2015-01-21T00:00:00.000000Z,2023-11-08T00:00:00.000000Z
20,361,Maluku Utara,9,4572,2015-03-19T00:00:00.000000Z,2023-09-26T00:00:00.000000Z
21,37,Nusa Tenggara Barat,9,1818,2014-12-17T00:00:00.000000Z,2023-09-06T00:00:00.000000Z
22,131,Nusa Tenggara Timur,9,3368,2015-01-30T00:00:00.000000Z,2023-10-11T00:00:00.000000Z
23,41,Papua,9,3560,2014-12-24T00:00:00.000000Z,2023-11-02T00:00:00.000000Z
24,641,Papua Barat,9,2711,2015-06-06T00:00:00.000000Z,2023-11-21T00:00:00.000000Z
25,39,Riau,9,4666,2014-12-24T00:00:00.000000Z,2023-11-09T00:00:00.000000Z
26,263,Sulawesi Barat,9,1465,2014-06-16T00:00:00.000000Z,2023-11-12T00:00:00.000000Z
27,36,Sulawesi Selatan,9,3556,2014-12-04T00:00:00.000000Z,2023-10-17T00:00:00.000000Z
28,154,Sulawesi Tengah,9,2182,2016-01-15T00:00:00.000000Z,2120-07-26T00:00:00.000000Z
29,81,Sulawesi Tenggara,9,5292,2015-01-20T00:00:00.000000Z,2023-11-16T00:00:00.000000Z
30,173,Sulawesi Utara,9,3399,2014-12-18T00:00:00.000000Z,2023-11-16T00:00:00.000000Z
31,16,Sumatera Barat,10,4150,2014-12-24T00:00:00.000000Z,2024-09-26T14:59:00.000000Z
32,103,Sumatera Selatan,9,5930,2015-01-30T00:00:00.000000Z,2023-11-10T00:00:00.000000Z
33,27,Sumatera Utara,10,5782,2014-12-16T00:00:00.000000Z,2024-11-13T15:29:00.000000Z

Saved files:
- Master CSV         : C:\Users\VICTUS\coding\collab\3\data\csv\master_data_ocds.csv
- Summary CSV        : C:\Users\VICTUS\coding\collab\3\data\csv\raw_data_summary_by_daerah.csv
- LPSE Catalog (all) : C:\Users\VICTUS\coding\collab\3\data\csv\lpse_catalog_all.csv
- LPSE Catalog prov  : C:\Users\VICTUS\coding\collab\3\data\csv\lpse_province_catalog.csv
- Total rows         : 145,922